//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuvirinimaiApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuvirinimaiApp.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ar tikrai tikrai apsisprendėte ištrinti?.
        /// </summary>
        internal static string Ar_tikrai_istrinti {
            get {
                return ResourceManager.GetString("Ar_tikrai_istrinti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netinkama reikšmė.
        /// </summary>
        internal static string Bloga_reiksme {
            get {
                return ResourceManager.GetString("Bloga_reiksme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šiai duomenų bazei nenustatyti prisijungimo parametrai (connection string). Programa nutraukiama..
        /// </summary>
        internal static string ConnectionString_not_set {
            get {
                return ResourceManager.GetString("ConnectionString_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepavyksta atlikti duomenų bazės užklausos..
        /// </summary>
        internal static string DbErrorMsg {
            get {
                return ResourceManager.GetString("DbErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įrašas sėkmingai išsaugotas.
        /// </summary>
        internal static string Irasas_issaugotas {
            get {
                return ResourceManager.GetString("Irasas_issaugotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įrašo išsaugoti nepavyko..
        /// </summary>
        internal static string Irasas_neissaugotas {
            get {
                return ResourceManager.GetString("Irasas_neissaugotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naujas įrašas sukurtas. Įveskite/pakoreguokite kitus jo duomenis, išsaugokite ir naudokite į sveikatą..
        /// </summary>
        internal static string Irasas_sukurtas {
            get {
                return ResourceManager.GetString("Irasas_sukurtas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodas turi būti išreikštas sveikuoju teigiamu skaičiumi..
        /// </summary>
        internal static string Kodas_turi_buti_skaicius {
            get {
                return ResourceManager.GetString("Kodas_turi_buti_skaicius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programa Suvirinimai.
        /// </summary>
        internal static string MsgBoxTitle {
            get {
                return ResourceManager.GetString("MsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jūsų mėginamas ištrinti objektas yra naudojamas kitur, todėl jo ištrinti negalima. Jeigu nenorite naudoti, galite pažymėti kaip neaktyvų..
        /// </summary>
        internal static string Naudojamas_negalima_istrinti {
            get {
                return ResourceManager.GetString("Naudojamas_negalima_istrinti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netinka įvesta reikšmė..
        /// </summary>
        internal static string Netinka_reiksme {
            get {
                return ResourceManager.GetString("Netinka_reiksme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netinkami duomenys, objektas su tokiais  duomenimis jau yra..
        /// </summary>
        internal static string Objektas_jau_yra {
            get {
                return ResourceManager.GetString("Objektas_jau_yra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negalima du kartus rikiuoti pagal tą patį stulpelį. Pagal stulpelį {0} sąrašas jau rikiuotas..
        /// </summary>
        internal static string Pagal_toki_jau_rikiuota {
            get {
                return ResourceManager.GetString("Pagal_toki_jau_rikiuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per ilgas filtras! Filtras turi būti ne ilgesnis kaip iš {0} salygų. Filtras bus nepilnas. Žr. būsenos juostą apačioje..
        /// </summary>
        internal static string Per_ilgas_filtras {
            get {
                return ResourceManager.GetString("Per_ilgas_filtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importas failino.{0}Priežastis: {1}.{0}Importuok į duomenų bazę kitais būdais arba paredaguok eksportuotą xml failą ir mėgink iš naujo..
        /// </summary>
        internal static string XmlImport_fail {
            get {
                return ResourceManager.GetString("XmlImport_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yra neišsaugotų pakeitimų. Ar išsaugoti?.
        /// </summary>
        internal static string Yra_pakeitimu_Ar_issaugoti {
            get {
                return ResourceManager.GetString("Yra_pakeitimu_Ar_issaugoti", resourceCulture);
            }
        }
    }
}
